import Foundation

// 热门 skill 目录（脚本生成，勿手改——scripts/gen-catalog-hot.py 全文件重生成）。
// 覆盖 skills.sh 排行 / anthropics 官方 / awesome 列表的常用 skill：
// 装了它们的用户不用等我们手工收录就有干净的双语一句话简介。
// 手工精选在 Catalog.swift，同名时手工版优先（Catalog.entry 的查找顺序保证）。

enum CatalogHot {
    static let skills: [String: CatalogEntry] = [
        "find-skills": .init(desc: "技能发现器：按需求搜索并安装生态内 skill", en: "Discover and install agent skills when users ask 'is there a skill for X'"),
        "frontend-design": .init(desc: "前端视觉设计指导：审美定调+字体排印，拒绝模板脸", en: "Intentional UI visual design guidance: aesthetic direction, typography, non-template look"),
        "vercel-react-best-practices": .init(desc: "Vercel 官方 React/Next.js 性能优化规范", en: "React/Next.js performance optimization guidelines from Vercel Engineering"),
        "agent-browser": .init(desc: "Agent 浏览器自动化 CLI：导航/填表/截图/取数", en: "Browser automation CLI for agents: navigate, fill forms, click, screenshot, extract data"),
        "grill-me": .init(desc: "拷问式追问，把方案和设计磨到无懈可击", en: "A relentless interview to sharpen a plan or design"),
        "web-design-guidelines": .init(desc: "UI 代码对标 Web 界面规范：无障碍与 UX 审查", en: "Review UI code for Web Interface Guidelines compliance: accessibility and UX audit"),
        "microsoft-foundry": .init(desc: "AI Foundry 智能体全流程：部署/评估/微调", en: "Deploy, evaluate, fine-tune and manage Azure AI Foundry agents end-to-end with azd"),
        "azure-ai": .init(desc: "Azure AI 服务：搜索/语音/OpenAI/文档智能", en: "Azure AI services: Search, Speech, OpenAI, Document Intelligence, vector search, OCR"),
        "azure-deploy": .init(desc: "执行 Azure 部署：azd 把就绪应用推上云", en: "Execute Azure deployments for already-prepared apps: azd up, hosting, pipelines"),
        "azure-diagnostics": .init(desc: "Azure 生产故障诊断：AppLens+Monitor 排障", en: "Debug Azure production issues with AppLens, Azure Monitor, resource health, safe triage"),
        "azure-prepare": .init(desc: "Azure 部署前准备：IaC 基建+容器化配置", en: "Prepare Azure apps for deployment: Bicep/Terraform infra, azure.yaml, Dockerfiles"),
        "azure-storage": .init(desc: "Azure 存储全案：Blob/队列/表/湖+分层策略", en: "Azure Storage guidance: Blob, File Shares, Queue, Table, Data Lake and access tiers"),
        "azure-validate": .init(desc: "Azure 部署前深检：配置/IaC/RBAC/前置条件", en: "Pre-deployment validation: config, Bicep/Terraform, RBAC, identity, prerequisites"),
        "entra-app-registration": .init(desc: "Entra ID 应用注册：OAuth2+MSAL 集成指南", en: "Microsoft Entra ID app registration, OAuth 2.0 authentication and MSAL integration"),
        "appinsights-instrumentation": .init(desc: "App Insights 埋点：遥测模式与 SDK 配置", en: "Instrument web apps with Azure Application Insights: telemetry patterns and SDK setup"),
        "azure-compliance": .init(desc: "Azure 合规安全审计：azqr+密钥过期巡检", en: "Azure compliance and security audits with azqr plus Key Vault expiration checks"),
        "azure-resource-lookup": .init(desc: "跨订阅查找罗列 Azure 资源清单", en: "List, find and show Azure resources across subscriptions and resource groups"),
        "azure-rbac": .init(desc: "RBAC 选角：最小权限+CLI/Bicep 赋权代码", en: "Find least-privilege Azure RBAC roles and generate CLI/Bicep assignment code"),
        "azure-aigateway": .init(desc: "APIM 作 AI 网关：语义缓存/限流/模型治理", en: "Configure Azure API Management as AI Gateway: caching, token limits, model governance"),
        "azure-kusto": .init(desc: "KQL 查询 Kusto/ADX：日志遥测时序分析", en: "Query Azure Data Explorer (Kusto) with KQL for logs, telemetry and time series"),
        "azure-resource-visualizer": .init(desc: "Azure 资源组分析，生成 Mermaid 架构图", en: "Analyze Azure resource groups and generate Mermaid architecture diagrams"),
        "azure-messaging": .init(desc: "Azure 消息 SDK 排障：事件中心/服务总线", en: "Troubleshoot Azure Event Hubs and Service Bus SDK issues: connection, auth, processing"),
        "remotion-best-practices": .init(desc: "Remotion 最佳实践：React 代码生成视频", en: "Best practices for Remotion: programmatic video creation in React"),
        "azure-hosted-copilot-sdk": .init(desc: "Copilot SDK 应用上 Azure：构建部署改造", en: "Build, deploy and modify GitHub Copilot SDK apps on Azure"),
        "grill-with-docs": .init(desc: "拷问式磨方案，顺手沉淀 ADR 与术语表", en: "Relentless plan-sharpening interview that also writes ADRs and a glossary as you go"),
        "improve-codebase-architecture": .init(desc: "扫码库找架构改进点，出报告逐项拷问", en: "Scan codebase for deepening opportunities, render visual HTML report, grill through picks"),
        "azure-compute": .init(desc: "Azure 虚机路由：选型/比价/伸缩集/自动扩缩", en: "Azure VM/VMSS router: provisioning, size recommendation, pricing, scale sets, autoscale"),
        "azure-cloud-migrate": .init(desc: "跨云迁移上 Azure：评估报告+代码转换", en: "Assess and migrate cross-cloud workloads to Azure with reports and code conversion"),
        "tdd": .init(desc: "测试驱动开发：红绿重构节奏做功能修 bug", en: "Test-driven development: red-green-refactor workflow for features and bug fixes"),
        "video-edit": .init(desc: "RunComfy 视频编辑路由：按意图选改片模型", en: "Edit existing video on RunComfy: smart router picks the right edit model for the intent"),
        "image-to-video": .init(desc: "RunComfy 图生视频路由：静图动画选对模型", en: "Animate any still image on RunComfy: routes intent to the best image-to-video model"),
        "nano-banana-2": .init(desc: "Nano Banana 2 文生图：附官方提示词打法", en: "Generate images with Google Nano Banana 2 on RunComfy with documented prompt patterns"),
        "nano-banana-edit": .init(desc: "Nano Banana 图改图：保主体换背景可批量", en: "Edit images with Nano Banana 2: identity-preserving edits, background swap, 20-img batch"),
        "image-edit": .init(desc: "RunComfy 图像编辑路由：意图匹配最优模型", en: "Edit images on RunComfy: smart router matches intent to the right edit model"),
        "flux-kontext": .init(desc: "Flux Kontext 精准局部改图：官方提示词加持", en: "Edit images with Flux 1 Kontext Pro: precise local edits with documented prompting"),
        "gpt-image-edit": .init(desc: "GPT Image 2 改图：改画面内文字，多语言", en: "Edit images with OpenAI GPT Image 2 edit endpoint: in-image text rewrite, multilingual"),
        "wan-2-7": .init(desc: "Wan 2.7 文生视频：多参考+音频驱动口型", en: "Text-to-video with Wan 2.7: multi-reference conditioning, audio-driven lip-sync"),
        "flux-2-klein": .init(desc: "Flux 2 Klein 快速出图：蒸馏版+提示词模板", en: "Generate images with Flux 2 Klein, BFL's distilled fast variant, with prompt patterns"),
        "happyhorse-1-0": .init(desc: "HappyHorse 文生视频：1080p 自带同步音频", en: "Text-to-video with HappyHorse 1.0: Video Arena #1, native 1080p with synced audio"),
        "seedance-v2": .init(desc: "Seedance 2.0 Pro 电影感短片：多模态参考", en: "Cinematic short video with ByteDance Seedance 2.0 Pro: multi-modal refs, synced audio"),
        "agentspace": .init(desc: "工作目录变直播网址：随时围观 Agent 产出", en: "Turn the agent's working folder into a live URL to watch, edit and comment from anywhere"),
        "remotion-render": .init(desc: "Remotion 代码渲染成 MP4：传 TSX 出成片", en: "Render React/Remotion TSX code to MP4 via inference.sh: full Remotion API support"),
        "ai-video-generation": .init(desc: "一个 CLI 调 40+ 视频模型：Veo/Seedance/Wan", en: "Generate AI video with Veo, Seedance, HappyHorse, Wan, Grok and 40+ models via one CLI"),
        "ai-avatar-video": .init(desc: "AI 数字人口播视频：自带 TTS 多模型可选", en: "Create AI avatar and talking-head videos with built-in TTS via inference.sh CLI"),
        "ai-image-generation": .init(desc: "一个 CLI 调 50+ 图像模型：GPT/FLUX/Seedream", en: "Generate images with GPT-Image-2, FLUX, Gemini, Seedream and 50+ models via one CLI"),
        "twitter-automation": .init(desc: "X/推特自动化：发帖/点赞/转推/私信/关注", en: "Automate Twitter/X via CLI: post tweets with media, like, retweet, DM, follow"),
        "to-prd": .init(desc: "对话直接沉淀成 PRD，发进 issue 跟踪器", en: "Turn the current conversation into a PRD and publish it to the project issue tracker"),
        "kling-3-0": .init(desc: "可灵 3.0 多镜头视频：原生音频+角色一致", en: "Kling 3.0 multi-shot video generation with native synced audio and consistent identity"),
        "to-issues": .init(desc: "方案拆成可独立认领的垂直切片 issue", en: "Break a plan, spec or PRD into independently-grabbable tracer-bullet issues"),
        "caveman": .init(desc: "原始人压缩话术：省 65% token 不丢准确性", en: "Ultra-compressed caveman speech mode: cuts output tokens 65% with full accuracy"),
        "sleek-design-mobile-apps": .init(desc: "Sleek 移动端 UI 设计，落地 RN/SwiftUI 代码", en: "Design mobile app UI screens with Sleek and implement them in HTML/React Native/SwiftUI"),
        "setup-matt-pocock-skills": .init(desc: "工程技能集初始化：跟踪器/标签/文档布局", en: "One-time repo setup for the engineering skills: issue tracker, triage labels, doc layout"),
        "codex-pet": .init(desc: "一张参考图生成 Codex 桌宠精灵图组件", en: "Generate a Codex-compatible pet spritesheet and pet.json from one reference image"),
        "azure-quotas": .init(desc: "Azure 配额管理：容量校验/选区/提额申请", en: "Check and manage Azure quotas and usage: capacity validation, region selection, increases"),
        "triage": .init(desc: "issue/PR 分诊流水线：归类核实出执行简报", en: "Move issues and external PRs through triage roles: categorise, verify, write agent briefs"),
        "azure-upgrade": .init(desc: "Azure 升级评估：换档位/SKU+SDK 现代化", en: "Assess and upgrade Azure workloads between plans, tiers, SKUs; modernize SDK dependencies"),
        "runcomfy-cli": .init(desc: "RunComfy 万能 CLI：一次认证跑全部模型", en: "One binary, one auth, hundreds of model endpoints: run any RunComfy model from CLI"),
        "face-swap": .init(desc: "视频图像换脸路由：动画/静帧各选最优模型", en: "Swap a face or character into video/images on RunComfy: routes to the right model"),
        "video-inpainting": .init(desc: "视频区域修补：跨帧除物/去水印/带运动替换", en: "Region edits across video frames: remove objects, clean watermarks, replace with motion"),
        "image-inpainting": .init(desc: "蒙版图像修补：专用端点+保身份编辑兜底", en: "Mask-driven image inpainting on RunComfy: dedicated endpoint plus identity-safe editors"),
        "controlnet-pose": .init(desc: "姿态控制生成：参考视频动作迁移到角色", en: "Pose-conditioned generation: transfer reference-video motion onto a target character"),
        "lipsync": .init(desc: "口型同步路由：肖像/视频对齐任意音轨", en: "Lip-sync a face to audio: routes OmniHuman, Sync Labs, Kling across portrait and video"),
        "video-extend": .init(desc: "视频续写：Veo 3.1 按提示词接着往下拍", en: "Extend an existing clip with Veo 3.1 extend-video: prompt what happens next"),
        "elevenlabs-music-generation": .init(desc: "ElevenLabs 写歌：风格+歌词出录音室级成品", en: "Full songs from style plus lyrics with ElevenLabs Music: studio-grade stereo, 5s-5min"),
        "image-outpainting": .init(desc: "图像扩边：补画面外内容，改比例不动主体", en: "Extend a still beyond its canvas: fill unseen areas, change aspect ratio, keep content"),
        "video-outpainting": .init(desc: "视频扩幅：竖转横补环境，中心动作不变", en: "Extend a video's spatial canvas: flip 9:16 to 16:9, add environment, keep the action"),
        "relight": .init(desc: "图像重打光：改光向/色温/氛围不伤画面", en: "Relight a still image: change lighting direction, color temperature and mood"),
        "ai-music": .init(desc: "AI 音乐路由：商用人声或开源模型按需选", en: "AI music router on RunComfy: ElevenLabs premium vocals or ACE Step open-weights"),
        "ace-step": .init(desc: "ACE Step 作曲：标签定曲风，歌词可多语言", en: "Generate, inpaint and outpaint music with ACE Step: tag-driven, multilingual lyrics"),
        "handoff": .init(desc: "会话压缩成交接文档，换个 Agent 无缝接力", en: "Compact the current conversation into a handoff document for another agent to pick up"),
        "github-actions-docs": .init(desc: "GitHub Actions 全科：语法/复用/安全/排障", en: "Write, explain, secure and troubleshoot GitHub Actions workflows and custom actions"),
        "supabase-postgres-best-practices": .init(desc: "Supabase 官方 Postgres 性能优化最佳实践", en: "Postgres performance optimization and best practices from Supabase"),
        "prototype": .init(desc: "一次性原型验证设计：状态模型/UI 手感", en: "Build a throwaway prototype to answer a design question about state models or UI feel"),
        "openclaw-secure-linux-cloud": .init(desc: "云上自托管 OpenClaw：隧道/沙箱/鉴权加固", en: "Self-host OpenClaw on a cloud server securely: tunneling, sandboxing, token auth"),
        "secure-linux-web-hosting": .init(desc: "自托管服务器加固：DNS/SSH/防火墙/HTTPS", en: "Set up and harden a self-hosting cloud server: DNS, SSH, firewall, Nginx, HTTPS"),
        "skills-cli": .init(desc: "skills CLI 管家：装/更/备份/同步技能", en: "Operate the skills CLI: discover, install, update, back up, sync agent skills"),
        "running-claude-code-via-litellm-copilot": .init(desc: "LiteLLM 转接 Copilot 跑 Claude Code 省钱", en: "Route Claude Code through a local LiteLLM proxy to GitHub Copilot to cut API spend"),
        "opensource-guide-coach": .init(desc: "开源项目教练：启动/治理/资金/社区健康", en: "Coach for starting, growing, governing, funding and sustaining open source projects"),
        "azure-enterprise-infra-planner": .init(desc: "企业级 Azure 架构规划，产出 IaC 代码", en: "Architect enterprise Azure infra from workload descriptions: WAF-aligned Bicep/Terraform"),
        "readme-i18n": .init(desc: "README 多语言化：翻译+语言切换器维护", en: "Translate a repository README and maintain multilingual doc variants with a switcher"),
        "use-my-browser": .init(desc: "借用户真实浏览器会话：登录态/本地/调试上下文", en: "Work inside the user's live browser session: logged-in dashboards, localhost, DevTools"),
        "xget": .init(desc: "Xget 链接改写：包/镜像/API 下载全面加速", en: "Xget URL rewriting to accelerate registries, packages, containers and API downloads"),
        "tzst": .init(desc: "tzst 归档工具：zstd 压缩包创建解压脚本化", en: "Create, extract, list and script .tzst / .tar.zst archives with the tzst CLI"),
        "xdrop": .init(desc: "Xdrop 终端传文件：加密分享链收发解密", en: "Send and fetch files through an Xdrop server: encrypted share links from the terminal"),
        "brainstorming": .init(desc: "动手前强制头脑风暴：意图/需求/设计先行", en: "Mandatory pre-work exploration of intent, requirements and design before implementation"),
        "azure-kubernetes": .init(desc: "AKS 生产集群规划：选型/网络/安全/运维", en: "Plan and configure production AKS clusters: SKU, networking, security, operations"),
        "ui-ux-pro-max": .init(desc: "UI/UX 大全：50 风格 161 配色 99 条 UX 军规", en: "UI/UX intelligence: 50+ styles, 161 palettes, 57 font pairs, 99 UX rules across 10 stacks"),
        "gpt-image-2": .init(desc: "GPT Image 2 生图改图：画面文字与标志强项", en: "Generate and edit images with GPT Image 2: embedded text, logos, multilingual typography"),
        "vercel-composition-patterns": .init(desc: "React 组合模式：复合组件/渲染属性/上下文", en: "Scalable React composition patterns: compound components, render props, context design"),
        "azure-cost": .init(desc: "Azure 成本管理：查账/预测/清孤儿资源", en: "Azure cost management: query spend, forecast, find orphaned resources, cut waste"),
        "diagnose": .init(desc: "疑难 bug 诊断环：复现最小化假设验证回归", en: "Disciplined diagnosis loop: reproduce, minimise, hypothesise, instrument, fix, regress"),
        "simple": .init(desc: "轻量版动手前头脑风暴：快速聚焦定方案", en: "Streamlined brainstorming before creative or architectural work: fast focused decisions"),
        "write-a-skill": .init(desc: "写新技能：结构规范+渐进披露+资源打包", en: "Create new agent skills with proper structure, progressive disclosure, bundled resources"),
        "just-scrape": .init(desc: "ScrapeGraph 抓取：搜索/爬站/结构化提取/监控", en: "Search, scrape, crawl and extract structured data via the ScrapeGraph AI CLI"),
        "zoom-out": .init(desc: "拉远视角：讲清代码在全局里的位置", en: "Zoom out for broader context: how this code fits into the bigger picture"),
        "shadcn": .init(desc: "shadcn/ui 管家：加组件/查文档/调样式/组界面", en: "Manage shadcn/ui components and projects: add, search, debug, style and compose UI"),
        "develop-userscripts": .init(desc: "油猴脚本开发：GM API/元数据块/发布全流程", en: "Build, debug, package and publish Tampermonkey/ScriptCat userscripts with GM APIs"),
        "design-taste-frontend": .init(desc: "反 AI 味前端：读需求定调性，拒绝模板脸", en: "Anti-slop frontend for landing pages and redesigns: infer direction, ship non-templated UI"),
        "caveman-commit": .init(desc: "极简 commit 生成：50 字符主题，废话全砍", en: "Ultra-compressed Conventional Commits: subject under 50 chars, body only when needed"),
        "caveman-review": .init(desc: "极简代码评审：一行一条，位置+问题+改法", en: "Ultra-compressed code review: one line per comment with location, problem, fix"),
        "azure-cost-optimization": .init(desc: "Azure 省钱分析：虚机瘦身+清废弃资源", en: "Identify Azure savings from usage data: rightsize VMs, delete orphans, cut waste"),
        "caveman-compress": .init(desc: "记忆文件原始人压缩：省 token 保留干货", en: "Compress CLAUDE.md and memory files into caveman format to save input tokens"),
        "caveman-help": .init(desc: "caveman 全家速查卡：模式/技能/命令一览", en: "Quick-reference card for all caveman modes, skills and commands"),
        "impeccable": .init(desc: "前端界面全能工坊：设计/审查/打磨一条龙", en: "Design, critique, audit and polish frontend interfaces with production-grade craft"),
        "airunway-aks-setup": .init(desc: "AKS 装 AI Runway：裸集群到模型跑通", en: "Set up AI Runway on AKS from bare cluster to running model: GPU, providers, deploy"),
        "systematic-debugging": .init(desc: "系统化排障：先找根因再谈修复", en: "Systematic root-cause debugging for any bug or test failure before proposing fixes"),
        "high-end-visual-design": .init(desc: "高端设计范式：字体间距阴影都往贵了做", en: "Design like a high-end agency: exact fonts, spacing, shadows that read expensive"),
        "writing-plans": .init(desc: "动码前先写实施计划：规格拆成步骤", en: "Turn a spec into a step-by-step implementation plan before touching code"),
        "using-superpowers": .init(desc: "superpowers 引导器：回答前先查该用哪个技能", en: "Session bootstrap that establishes how to find and invoke skills before any response"),
        "redesign-existing-projects": .init(desc: "旧站升级高端化：审计除 AI 味，功能不破坏", en: "Upgrade existing sites to premium quality: audit, kill generic AI patterns, keep function"),
        "teach": .init(desc: "工作区内因材施教：讲透一个概念或技能", en: "Teach the user a new skill or concept within this workspace"),
        "hyperframes": .init(desc: "HTML 渲染视频总入口：宣传片/解说/动效", en: "Render video from HTML: entry skill for promos, explainers, captions, motion graphics"),
        "cavecrew": .init(desc: "原始人分工指南：查码/改码/审码派对人", en: "Decision guide for delegating to caveman subagents: investigator, builder, reviewer"),
        "caveman-stats": .init(desc: "token 账本：真实用量与节省，读日志不估算", en: "Show real token usage and estimated savings for the session from the actual log"),
        "hyperframes-cli": .init(desc: "HyperFrames CLI 闭环：初始化到渲染发布", en: "HyperFrames CLI dev loop: init, add, capture, lint, render, publish, doctor"),
        "vercel-react-native-skills": .init(desc: "RN/Expo 最佳实践：列表/动画/原生模块", en: "React Native and Expo best practices: lists, animations, native modules, performance"),
        "minimalist-ui": .init(desc: "极简编辑风 UI：暖调单色+字阶对比+便当格", en: "Clean editorial interfaces: warm monochrome, typographic contrast, flat bento grids"),
        "hyperframes-registry": .init(desc: "HyperFrames 组件库：装块并接入合成", en: "Install and wire HyperFrames registry blocks and components into compositions"),
        "requesting-code-review": .init(desc: "完工必审：合并前对照需求验收", en: "Request verification that completed work meets requirements before merging"),
        "seo-audit": .init(desc: "SEO 体检：技术项/页内优化/掉排名归因", en: "Audit and diagnose site SEO: technical issues, on-page, meta tags, ranking drops"),
        "test-driven-development": .init(desc: "任何功能修复先写失败测试，再写实现", en: "Write the failing test first: TDD discipline for any feature or bugfix"),
        "supabase": .init(desc: "Supabase 全家桶：库/鉴权/边缘函数/实时/存储", en: "One skill for all Supabase work: Database, Auth, Edge Functions, Realtime, Storage, SSR"),
        "entra-agent-id": .init(desc: "Entra Agent 身份编排：蓝图+OAuth 令牌交换", en: "Provision Entra Agent Identity blueprints and OAuth token exchange via Microsoft Graph"),
        "full-output-enforcement": .init(desc: "强制完整输出：禁占位符，超长干净分段", en: "Override truncation: enforce complete code output, ban placeholders, split cleanly"),
        "industrial-brutalist-ui": .init(desc: "工业粗野风 UI：瑞士排印×军用终端美学", en: "Raw mechanical interfaces: Swiss print meets military terminal, rigid grids, analog decay"),
        "stitch-design-taste": .init(desc: "Stitch 设计基因文件：反平庸 UI 标准落纸", en: "Generate agent-friendly DESIGN.md for Google Stitch enforcing premium anti-generic UI"),
        "copywriting": .init(desc: "营销文案：首页/落地页/定价页写改一手包", en: "Write and improve marketing copy for homepage, landing, pricing and product pages"),
        "executing-plans": .init(desc: "按计划施工：独立会话执行+检查点回看", en: "Execute a written implementation plan in a separate session with review checkpoints"),
        "paper-context-resolver": .init(desc: "论文复现补细节：数据切分/预处理/评测口径", en: "Resolve reproduction-critical paper details: dataset splits, preprocessing, eval metrics"),
        "repo-intake-and-plan": .init(desc: "复现前扫仓：读 README 提命令排复现计划", en: "Scan a deep learning repo README-first, extract commands, plan reproduction candidates"),
        "minimal-run-and-audit": .init(desc: "最小复现跑通：证据规范化存档可审计", en: "Run the chosen smoke test and normalize evidence into standardized repro_outputs files"),
        "env-and-assets-bootstrap": .init(desc: "复现环境引导：conda/权重/数据路径先备齐", en: "Prepare conda-first environment, checkpoints and dataset paths before repo reproduction"),
        "gpt-taste": .init(desc: "GSAP 高级动效 UX：真随机布局+AIDA 结构", en: "Elite UX with advanced GSAP motion: random layout variance, AIDA structure, bento grids"),
        "remotion-to-hyperframes": .init(desc: "Remotion 工程平移 HyperFrames HTML", en: "Port an existing Remotion React composition to HyperFrames HTML"),
        "subagent-driven-development": .init(desc: "子代理开发法：独立任务分头并行执行", en: "Dispatch independent plan tasks to subagents within the current session"),
        "hyperframes-media": .init(desc: "HyperFrames 音频资产：TTS/配乐/音效一站", en: "Audio and media assets for HyperFrames: multi-provider TTS, music and sound effects"),
        "verification-before-completion": .init(desc: "宣称完成前必须跑验证：证据先于结论", en: "Run verification commands and confirm output before any claim of done, fixed or passing"),
        "brandkit": .init(desc: "高端品牌套件生成：规范板/标志系统/识别集", en: "Generate premium brand kits: guideline boards, logo systems, identity decks"),
        "receiving-code-review": .init(desc: "接评审不盲从：先验证再改，拒绝表演式认同", en: "Handle review feedback with technical rigor: verify before implementing suggestions"),
        "image-to-code": .init(desc: "先生成设计图再逐像素实现网页", en: "Generate design images first, analyze deeply, then implement the website to match"),
        "writing-skills": .init(desc: "技能工程：写/改/验证 skill 再上线", en: "Create, edit and verify agent skills before deployment"),
        "extract-design-system": .init(desc: "扒站提设计体系：产出可用的 token 起步包", en: "Extract design primitives from a public website and generate starter token files"),
        "imagegen-frontend-web": .init(desc: "网页设计参考图：每个区块单独出一张横图", en: "Generate premium website design references: one horizontal image per page section"),
        "dispatching-parallel-agents": .init(desc: "并行派单：无依赖任务多代理同时开工", en: "Dispatch parallel agents for 2+ independent tasks without shared state"),
        "using-git-worktrees": .init(desc: "git worktree 隔离工作区，开发互不打架", en: "Ensure isolated workspaces for feature work via git worktree"),
        "imagegen-frontend-mobile": .init(desc: "移动端界面概念图：iOS/安卓多屏一致出图", en: "Generate premium app-native mobile screen concepts and flows for iOS and Android"),
        "viral-short-form": .init(desc: "短视频爆款内容：高留存脚本与轮播策划", en: "Brainstorm and write high-retention short-form video and carousel content"),
        "finishing-a-development-branch": .init(desc: "分支收尾决策：合并/提 PR/清理怎么选", en: "Structured completion options when tests pass: merge, PR, or cleanup"),
        "emil-design-eng": .init(desc: "Emil 设计工学：UI 打磨与动画的隐形细节", en: "Emil Kowalski's philosophy on UI polish, component design and animation decisions"),
        "viral-hooks": .init(desc: "爆款钩子：开头 3 秒的生死判官", en: "Write and critique viral hooks: the opening 1-3 seconds that decide everything"),
        "viral-youtube-shorts": .init(desc: "YouTube Shorts 脚本：留住人再导流长视频", en: "Write YouTube Shorts that hold the feed and route viewers into long-form"),
        "viral-captions-and-ctas": .init(desc: "短视频文案配件：标题话题 CTA 不踩降权线", en: "Captions, on-screen text, hashtags and CTAs that earn saves without bait penalties"),
        "viral-short-form-ideas": .init(desc: "选题弹药库：批量产短视频创意不卡壳", en: "Generate short-form video ideas at volume: kill the blank-page problem"),
        "viral-instagram-reels": .init(desc: "Reels 冷启动：脚本策划+扑街诊断", en: "Plan, write and diagnose Instagram Reels for cold-audience reach"),
        "viral-tiktok-content": .init(desc: "TikTok 内容：按 FYP 推荐逻辑定制脚本", en: "TikTok scripts, hooks and ideas shaped for how the FYP actually ranks"),
        "azure-reliability": .init(desc: "Azure 可靠性体检：容灾冗余/探针/多区切换", en: "Assess PaaS reliability posture: zone redundancy, health probes, multi-region failover"),
        "webapp-testing": .init(desc: "Playwright 测本地 Web 应用：验证 UI、截图、抓日志", en: "Test local web apps with Playwright: verify UI, debug, screenshots, browser logs"),
        "marketing-psychology": .init(desc: "营销心理学：认知偏差与购买决策的用法", en: "Apply behavioral science to marketing: cognitive bias, persuasion, why people buy"),
        "design-an-interface": .init(desc: "接口设计多方案：并行子代理各出一版", en: "Generate radically different interface designs for a module with parallel subagents"),
        "request-refactor-plan": .init(desc: "重构计划访谈：小步提交拆解成 issue", en: "Interview-driven refactor plan with tiny commits, filed as a GitHub issue"),
        "content-strategy": .init(desc: "内容策略：写什么/主题集群/博客排期", en: "Plan content strategy: what to write, topic clusters, blog planning"),
        "firebase-basics": .init(desc: "Firebase CLI 基础：初始化/鉴权/项目管理", en: "Firebase CLI foundations: setup, authentication and project management workflows"),
        "azure-observability": .init(desc: "Azure 可观测：监控/APM/日志分析/告警", en: "Azure observability: Monitor, App Insights, Log Analytics, alerts, KQL, workbooks"),
        "ubiquitous-language": .init(desc: "DDD 术语表提炼：统一语言，标出歧义", en: "Extract a DDD ubiquitous-language glossary from conversation, flag ambiguities"),
        "firebase-auth-basics": .init(desc: "Firebase 认证接入：登录/用户管理/安全规则", en: "Set up Firebase Authentication: sign-in, user management, secure data access rules"),
        "sentry-cli": .init(desc: "Sentry CLI 操作：查问题/事件/项目/调 API", en: "Use the Sentry CLI: view issues, events, projects, orgs, API calls, authentication"),
        "qa": .init(desc: "对话式 QA：口头报 bug，自动查码提 issue", en: "Conversational QA: report bugs in chat, agent explores codebase and files GitHub issues"),
        "programmatic-seo": .init(desc: "程序化 SEO：模板+数据批量造页抢长尾", en: "SEO pages at scale from templates and data: directory, location, comparison pages"),
        "analyze-project": .init(desc: "炼丹仓只读体检：结构/入口/配置/可疑点", en: "Read-only deep learning repo audit: model structure, entrypoints, configs, red flags"),
        "ai-research-explore": .init(desc: "科研选题探索：给定基准约束下找新点子", en: "Candidate-only exploration for novel DL research given task, dataset and SOTA refs"),
        "explore-code": .init(desc: "隔离分支试验改造：移植模块换骨干可审计", en: "Auditable candidate implementation on isolated branch: transplant modules, adapt backbones"),
        "ai-research-reproduction": .init(desc: "论文仓库端到端复现：README 优先最小可信", en: "End-to-end README-first repo reproduction with minimal trustworthy targets"),
        "safe-debug": .init(desc: "炼丹排障：OOM/形状不符/NaN 先诊断后动手", en: "Conservative DL debugging: tracebacks, CUDA OOM, shape mismatch, NaN loss diagnosis"),
        "run-train": .init(desc: "训练执行规程：试跑验证再全量，断点可续", en: "Run training conservatively: startup check, short-run verify, kickoff, resume"),
        "explore-run": .init(desc: "探索性小跑：子集验证/短周期扫参留证据", en: "Bounded exploratory runs: small-subset validation, short-cycle sweeps with evidence"),
        "git-guardrails-claude-code": .init(desc: "git 护栏钩子：拦截强推/硬重置等危险命令", en: "Claude Code hooks that block dangerous git commands before they execute"),
        "firebase-hosting-basics": .init(desc: "Firebase Hosting 部署：静态站/SPA 上线", en: "Deploy static sites, SPAs and simple microservices with Firebase Hosting"),
        "firebase-app-hosting-basics": .init(desc: "App Hosting 部署带后端的 Next/Angular", en: "Deploy and manage Next.js/Angular apps with backends on Firebase App Hosting"),
        "obsidian-vault": .init(desc: "Obsidian 笔记管家：搜索/新建/双链组织", en: "Search, create and organize Obsidian notes with wikilinks and index notes"),
        "grilling": .init(desc: "开工前压力测试：把计划拷问到站得住", en: "Grill the user relentlessly to stress-test a plan before building"),
        "firebase-data-connect": .init(desc: "Data Connect 后端：PG 建模+授权查询+SDK", en: "Build Firebase Data Connect backends on PostgreSQL: schemas, authorized queries, SDKs"),
        "marketing-ideas": .init(desc: "SaaS 营销点子库：增长策略与推广打法", en: "Marketing and growth ideas for SaaS products: strategies, tactics, promotion channels"),
        "edit-article": .init(desc: "文章精修：调结构/提清晰度/收紧行文", en: "Edit articles: restructure sections, improve clarity, tighten prose"),
        "gsap": .init(desc: "GSAP 动画速查：补间/缓动/时间轴/性能", en: "GSAP animation reference: tweens, easing, stagger, timelines, performance"),
        "setup-pre-commit": .init(desc: "pre-commit 三件套：格式化/类型检查/测试", en: "Set up Husky pre-commit hooks with lint-staged, type checking and tests"),
        "review": .init(desc: "双轴评审：既查编码规范又对需求规格", en: "Review changes since a fixed point on two axes: repo standards and spec compliance"),
        "scaffold-exercises": .init(desc: "课程练习脚手架：题目/答案/讲解一键成型", en: "Scaffold course exercise structures: sections, problems, solutions, explainers"),
        "website-to-hyperframes": .init(desc: "网站一键成片：抓站生成宣传/导览视频", en: "Capture a website and turn it into a HyperFrames video: promos, tours, social ads"),
        "domain-modeling": .init(desc: "领域建模：定术语/记决策/供其他技能调用", en: "Build and sharpen a project's domain model, terminology and architecture decisions"),
        "copy-editing": .init(desc: "营销文案精修：校对/收紧/翻新旧内容", en: "Edit and polish existing marketing copy: proofread, tighten, refresh outdated content"),
        "migrate-to-shoehorn": .init(desc: "测试类型断言迁移 shoehorn，告别 as", en: "Migrate test files from `as` type assertions to @total-typescript/shoehorn"),
        "codebase-design": .init(desc: "深模块设计词汇表：接口/切缝/可测性", en: "Shared vocabulary for designing deep modules: interfaces, seams, testability"),
        "writing-shape": .init(desc: "写作塑形：素材逐段捏成文章", en: "Shape raw writing material into an article, paragraph by paragraph"),
        "writing-fragments": .init(desc: "写作挖矿：先攒碎片素材，不急结构", en: "Mine raw writing fragments with no structure yet: the explore phase"),
        "writing-great-skills": .init(desc: "技能写作要诀：让 skill 触发得稳用得准", en: "Reference for writing predictable, well-structured agent skills"),
        "writing-beats": .init(desc: "写作节拍法：概念先落地再层层推进", en: "Assemble raw material into a journey of beats, grounding each term first"),
        "diagnosing-bugs": .init(desc: "硬 bug 诊断环：先复现定位，后谈修复", en: "Diagnosis loop for hard bugs and performance regressions before any fix"),
        "polish": .init(desc: "上线前抛光：对齐/间距/一致性/微细节", en: "Final quality pass before shipping: alignment, spacing, consistency, micro-details"),
        "firecrawl": .init(desc: "Firecrawl 抓取：搜索/爬站/提取三合一", en: "Search, scrape and crawl the web via the Firecrawl CLI: research, extract, monitor"),
        "design-taste-frontend-v1": .init(desc: "taste-skill 初代存档版：兼容老项目", en: "The original v1 taste-skill, preserved for exact backward compatibility"),
        "deploy-to-vercel": .init(desc: "一键部署 Vercel：上线或出预览链接", en: "Deploy apps and websites to Vercel: push live or create preview deployments"),
        "mcp-builder": .init(desc: "MCP 服务器开发指南：Python/TS 封装外部 API", en: "Build quality MCP servers in Python (FastMCP) or TypeScript to wrap external APIs as tools"),
        "ai-seo": .init(desc: "AI 搜索优化(GEO)：让大模型引用你的内容", en: "Optimize content for AI search engines: get cited by LLMs, appear in AI answers"),
        "critique": .init(desc: "设计评鉴：视觉层级/认知负荷量化打分", en: "UX-perspective design evaluation: hierarchy, cognitive load, scored actionable feedback"),
        "audit": .init(desc: "技术质检：无障碍/性能/主题/响应式评分报告", en: "Technical quality checks: accessibility, performance, theming, responsive, anti-patterns"),
        "animate": .init(desc: "有目的的动效：微交互提升可用性与愉悦感", en: "Enhance features with purposeful animations and micro-interactions that aid usability"),
        "adapt": .init(desc: "多端适配：断点/流式布局/触控目标", en: "Adapt designs across screens and devices: breakpoints, fluid layouts, touch targets"),
        "browser-use": .init(desc: "CDP 直控浏览器：自动化/抓取/测试/截图", en: "Direct browser control via CDP: automation, scraping, testing, screenshots"),
        "clarify": .init(desc: "界面文案优化：报错/微文案/标签说人话", en: "Improve UX copy: error messages, microcopy, labels and instructions people understand"),
        "optimize": .init(desc: "UI 性能诊治：加载/渲染/动画/包体积", en: "Diagnose and fix UI performance: loading, rendering, animations, images, bundle size"),
        "colorize": .init(desc: "配色注入：灰淡界面加对色彩的经营", en: "Add strategic color to monochromatic interfaces to make them engaging and expressive"),
        "canvas-design": .init(desc: "设计哲学驱动的海报与静态视觉，输出 PNG/PDF", en: "Create original posters and static visual art as PNG/PDF guided by design philosophy"),
        "ask-matt": .init(desc: "技能导航台：问一句该用哪个 skill", en: "Router over Matt Pocock's skills: ask which skill or flow fits your situation"),
        "bolder": .init(desc: "设计加胆量：平庸变有冲击力，可用性不丢", en: "Amplify safe, boring designs for more visual impact while keeping usability"),
        "delight": .init(desc: "惊喜感注入：让界面从能用变难忘", en: "Add joy, personality and unexpected touches that make interfaces memorable"),
        "distill": .init(desc: "设计做减法：去冗杂，留本质", en: "Strip designs to their essence: remove complexity, declutter, sharpen focus"),
        "quieter": .init(desc: "设计降噪：太吵的界面调成克制高级", en: "Tone down loud, overstimulating designs into a calmer, refined aesthetic"),
        "convex-quickstart": .init(desc: "Convex 快速起步：建项目接前端跑通", en: "Create or add Convex to an app: project setup, frontend wiring, first convex dev run"),
        "convex-performance-audit": .init(desc: "Convex 性能审计：读写争用/订阅/限额", en: "Audit Convex performance: reads, subscriptions, write contention, function limits"),
        "convex-setup-auth": .init(desc: "Convex 鉴权搭建：登录/身份映射/权限", en: "Set up Convex auth: providers, identity mapping, users tables, protected functions"),
        "convex-migration-helper": .init(desc: "Convex 迁移规划：改表回填零停机上线", en: "Plan Convex schema and data migrations: widen-migrate-narrow, zero-downtime rollouts"),
        "convex-create-component": .init(desc: "Convex 组件开发：隔离表+对外 API", en: "Build reusable Convex components with isolated tables and app-facing APIs"),
        "higgsfield-generate": .init(desc: "Higgsfield 多模态生成：图/视频/3D/音频", en: "Generate images, video, 3D and audio via Higgsfield AI with sensible model defaults"),
        "browser-act": .init(desc: "browser-act 浏览器自动化：会话与动作编排", en: "Browser automation CLI for agents: sessions, actions and page workflows"),
        "ad-creative": .init(desc: "广告素材量产：标题/正文/多版本迭代", en: "Generate and scale ad creative: headlines, primary text, full variations per platform"),
        "web-artifacts-builder": .init(desc: "复杂 Claude 网页产物：React+Tailwind+shadcn", en: "Build complex multi-component claude.ai artifacts with React, Tailwind CSS and shadcn/ui"),
        "playwright-cli": .init(desc: "Playwright CLI：浏览器自动化与测试", en: "Automate browser interactions, test web pages and work with Playwright tests"),
        "cold-email": .init(desc: "B2B 冷邮件：开发信+跟进序列要回复率", en: "B2B cold emails and follow-up sequences that get replies: prospecting, SDR campaigns"),
        "site-architecture": .init(desc: "网站信息架构：层级/导航/URL/内链规划", en: "Plan site page hierarchy, navigation, URL structure and internal linking"),
        "css-animations": .init(desc: "HyperFrames 的 CSS 动画：可寻帧确定渲染", en: "CSS keyframe animation patterns HyperFrames can seek deterministically"),
        "vercel-react-view-transitions": .init(desc: "React 视图过渡 API：原生手感页面动画", en: "Implement native-feeling animations with React's View Transition API"),
        "churn-prevention": .init(desc: "流失防治：挽留弹窗/救单优惠/催缴回款", en: "Reduce churn: cancellation flows, save offers, dunning, failed payment recovery"),
        "sales-enablement": .init(desc: "销售武器库：路演稿/一页纸/异议应对", en: "Create sales collateral: pitch decks, one-pagers, objection handling, demo scripts"),
        "tailwind": .init(desc: "HyperFrames 里的 Tailwind v4 用法", en: "Tailwind CSS v4 browser-runtime patterns for HyperFrames compositions"),
        "animejs": .init(desc: "Anime.js 接入 HyperFrames：可寻帧时间轴", en: "Anime.js adapter patterns: seek-driven deterministic timelines in HyperFrames"),
        "three": .init(desc: "Three.js 接入：确定性 3D 场景与镜头", en: "Three.js/WebGL adapter patterns: deterministic scenes, camera motion, shaders"),
        "lottie": .init(desc: "Lottie 接入：AE 导出动画确定性渲染", en: "Lottie and dotLottie adapter patterns: deterministic After Effects exports"),
        "firecrawl-scrape": .init(desc: "任意 URL 提净版 Markdown，SPA 也能啃", en: "Extract clean markdown from any URL, including JavaScript-rendered SPAs"),
        "firecrawl-search": .init(desc: "带全文抽取的联网搜索：查题找源", en: "Web search with full page content extraction: research topics, find sources"),
        "waapi": .init(desc: "WAAPI 原生动画：currentTime 精准寻帧", en: "Web Animations API adapter patterns: element.animate with deterministic seeking"),
        "revops": .init(desc: "RevOps 收入运营：线索评分/流转/部门交接", en: "Revenue operations: lead scoring and routing, MQL/SQL stages, marketing-sales handoff"),
        "better-auth-best-practices": .init(desc: "Better Auth 配置：适配器/会话/插件/OAuth", en: "Configure Better Auth server and client: adapters, sessions, plugins, OAuth"),
        "firecrawl-crawl": .init(desc: "整站批量抓取：顺链爬全站或文档区", en: "Bulk extract content from an entire site or docs section by following links"),
        "firecrawl-agent": .init(desc: "AI 自主取数：闯复杂网站，按 schema 出 JSON", en: "Autonomous data extraction: navigates complex sites, returns schema-shaped JSON"),
        "social-content": .init(desc: "社媒内容：多平台帖子/话题串/内容日历", en: "Create and optimize social content for LinkedIn, X, Instagram, TikTok: calendars, threads"),
        "firecrawl-map": .init(desc: "网站测绘：列全站 URL，可关键词过滤", en: "Discover and list all URLs on a website with optional search filtering"),
        "firecrawl-download": .init(desc: "整站离线打包：存成 Markdown/截图多格式", en: "Download an entire website as local files: markdown, screenshots, multiple formats"),
        "hyperframes-animation": .init(desc: "HyperFrames 动画总纲：规则/蓝图/七适配器", en: "All HyperFrames animation knowledge: motion rules, scene blueprints, seven adapters"),
        "typeset": .init(desc: "字排诊所：字体层级字号字重可读性", en: "Fix typography: font choices, hierarchy, sizing, weight and readability"),
        "hyperframes-core": .init(desc: "HyperFrames 合成契约：结构/时序/轨道", en: "The HyperFrames composition contract: structure, timing attributes, tracks, validation"),
        "motion-graphics": .init(desc: "动态图形：动态字/数字跳动/角标/片头标版", en: "Design-led motion graphics: kinetic type, count-ups, logo stings, lower-thirds"),
        "hyperframes-creative": .init(desc: "视频创意导演：设计规格/配色/旁白/节拍", en: "Creative direction for HyperFrames videos: design specs, palettes, narration, beats"),
        "general-video": .init(desc: "通用视频工作流：混剪/长片/自由合成兜底", en: "Fallback workflow for custom HyperFrames compositions: reels, montages, any length"),
        "theme-factory": .init(desc: "产物主题工厂：10 套预置配色字体，可即席生成", en: "Style artifacts with 10 preset color/font themes or generate new themes on the fly"),
        "lead-magnets": .init(desc: "引流钩子设计：白皮书/清单/模板换邮箱", en: "Create and optimize lead magnets: gated content, ebooks, checklists, templates"),
        "doc-coauthoring": .init(desc: "文档共创流程：传上下文、迭代打磨、读者验证", en: "Structured co-authoring workflow for docs, proposals, specs: iterate and verify"),
        "website-to-video": .init(desc: "网址变视频：站点导览/展示/社媒短片", en: "Capture a website and turn it into a site tour, showcase or social clip"),
        "product-launch-video": .init(desc: "产品发布视频：链接或脚本直出宣传片", en: "Turn a product URL, script or brief into a launch video: SaaS promos, feature reveals"),
        "faceless-explainer": .init(desc: "无真人解说视频：文字进成片出，视觉全造", en: "Turn any text into a faceless explainer video with invented visuals, 30-90s sweet spot"),
        "embedded-captions": .init(desc: "口播视频加字幕：32 种视觉风格可选", en: "Add captions to talking-head video: 32 visual identities, scene-composited or overlay"),
        "pr-to-video": .init(desc: "PR 变解说视频：代码变更可视化走查", en: "Turn a GitHub pull request into a code-change explainer video"),
        "overdrive": .init(desc: "界面开挂：着色器/弹簧物理/60 帧炫技", en: "Push interfaces past conventional limits: shaders, spring physics, 60fps reveals"),
        "brand-guidelines": .init(desc: "为产物套用 Anthropic 官方品牌色与字体规范", en: "Apply Anthropic's official brand colors and typography to any artifact"),
        "algorithmic-art": .init(desc: "p5.js 生成艺术：种子随机、流场、粒子系统", en: "Create algorithmic/generative art with p5.js: seeded randomness, flow fields, particles"),
        "vercel-cli-with-tokens": .init(desc: "令牌驱动 Vercel CLI：免交互部署管理", en: "Deploy and manage Vercel projects with token-based auth, no interactive login"),
        "higgsfield-product-photoshoot": .init(desc: "产品摄影级出图：棚拍/生活方式/主图", en: "Brand-quality product images via prompt enhancement on GPT Image 2"),
        "developing-genkit-js": .init(desc: "Genkit JS 开发：AI 流程/工具/排错", en: "Build AI apps with Genkit in Node/TypeScript: agents, flows, tools, debugging"),
        "firebase-security-rules-auditor": .init(desc: "Firestore 规则安检：改动即审强度", en: "Evaluate Firestore security rules for robustness whenever they change"),
        "developing-genkit-dart": .init(desc: "Genkit Dart：Flutter 应用接 AI 流程", en: "Genkit Dart SDK: build AI agents and LLM flows in Dart/Flutter apps"),
        "higgsfield-soul-id": .init(desc: "数字分身训练：人脸建模生成本人图像视频", en: "Train a Soul Character on a person's face for identity-faithful image and video"),
        "product-marketing-context": .init(desc: "产品营销底稿：定位/ICP/目标人群一次讲清", en: "Create the product marketing context doc: positioning, ICP, target audience"),
        "pricing-strategy": .init(desc: "定价策略：分层/免费增值/价值锚/提价", en: "Pricing, packaging and monetization: tiers, freemium, value metrics, price increases"),
        "firebase-ai-logic-basics": .init(desc: "Firebase AI Logic 接 Gemini：多模态输出", en: "Integrate Firebase AI Logic (Gemini API) into web apps: multimodal, structured output"),
        "browser-act-skill-forge": .init(desc: "探站一次铸成 skill：内部 API 沉淀复用", en: "Forge reusable skill packages from website exploration: capture internal APIs once"),
        "higgsfield-marketplace-cards": .init(desc: "电商主图套装：合规主图/副图/A+ 模块", en: "Marketplace product cards: compliant main image, secondary shots, A+ modules"),
        "implement": .init(desc: "按 PRD/issue 清单老实施工交付", en: "Implement a piece of work based on a PRD or set of issues"),
        "firebase-firestore": .init(desc: "Firestore 建库查询：全文检索+管道联表", en: "Set up and query Cloud Firestore: full-text search, relational joins via pipelines"),
        "customer-research": .init(desc: "客户研究：访谈/问卷/工单里挖真声音", en: "Conduct and synthesize customer research: interviews, surveys, support ticket mining"),
        "audit-website": .init(desc: "网站体检：240+ 规则出健康分与修复清单", en: "Audit sites across SEO, performance, security with 240+ rules and health scores"),
        "analytics-tracking": .init(desc: "埋点分析：GA4/转化事件/UTM/GTM 配齐", en: "Set up and audit analytics: GA4, conversion events, UTM parameters, tag manager"),
        "page-cro": .init(desc: "页面转化优化：首页/落地页/定价页 CRO", en: "Optimize conversions on any marketing page: homepage, landing, pricing, blog"),
        "building-native-ui": .init(desc: "Expo Router 原生 UI：样式/导航/动画全指南", en: "Build beautiful apps with Expo Router: styling, navigation, animations, native tabs"),
        "firebase-crashlytics": .init(desc: "Crashlytics 崩溃上报：接入配置全流程", en: "Set up Firebase Crashlytics: provisioning, SDK usage, crash reporting"),
        "playwright-best-practices": .init(desc: "Playwright 军规：治抖动/POM/CI/mock", en: "Playwright testing best practices: flaky fixes, POM, CI/CD, mocking, accessibility"),
        "xcode-project-setup": .init(desc: "Xcode 工程安全改装：加 Swift 包不弄坏", en: "Safely modify Xcode .pbxproj to add Swift Packages and link files"),
        "slideshow": .init(desc: "HyperFrames 幻灯片：分步显现/分支/热区", en: "Author HyperFrames slideshows: decks with fragment reveals, branching, hotspots"),
        "launch-strategy": .init(desc: "发布战役策划：PH 打榜/GTM/内测/候补名单", en: "Plan product launches: Product Hunt, go-to-market, beta, waitlists, announcements"),
        "schema-markup": .init(desc: "结构化数据：JSON-LD 富摘要各类 schema", en: "Add and optimize schema.org structured data: JSON-LD, rich snippets, FAQ schema"),
        "internal-comms": .init(desc: "企业内部通讯写作：状态周报/高层更新/事故通报", en: "Write internal comms: status reports, leadership updates, newsletters, incident reports"),
        "contribute-catalog": .init(desc: "HyperFrames 投稿：新组件做完提上游 PR", en: "Author a new HyperFrames registry block or component and ship it as an upstream PR"),
        "email-sequence": .init(desc: "邮件序列：滴灌/新手引导/生命周期自动化", en: "Create email sequences: drip campaigns, onboarding flows, lifecycle programs"),
        "normalize": .init(desc: "设计系统归位：间距/令牌/样式漂移矫正", en: "Audit and realign UI to design system standards: spacing, tokens, patterns"),
        "paid-ads": .init(desc: "投流全案：谷歌 Meta 领英/ROAS/再营销", en: "Paid campaigns on Google, Meta, LinkedIn: PPC, ROAS, retargeting, audience targeting"),
        "convex": .init(desc: "Convex 总路由：模糊需求分发到对的技能", en: "Route general Convex requests to the right project skill"),
        "competitor-alternatives": .init(desc: "竞品对比页：vs 页/替代品页双吃 SEO 销售", en: "Create competitor comparison and alternative pages for SEO and sales"),
        "extract": .init(desc: "设计系统萃取：重复 UI 沉淀成组件令牌", en: "Extract reusable components, tokens and patterns into your design system"),
        "onboarding-cro": .init(desc: "新手激活优化：首跑体验缩短见值时间", en: "Optimize post-signup onboarding: activation rate, first-run experience, time-to-value"),
        "onboard": .init(desc: "引导流设计：空状态/首次体验快速到价值", en: "Design onboarding flows, empty states and first-run experiences that reach value fast"),
        "harden": .init(desc: "界面加固：报错/空态/国际化/边界全兜住", en: "Make interfaces production-ready: error handling, empty states, i18n, edge cases"),
        "slack-gif-creator": .init(desc: "制作 Slack 专用动图：尺寸约束+校验工具", en: "Create animated GIFs optimized for Slack with size constraints and validation tools"),
        "form-cro": .init(desc: "表单转化优化：留资/联系/演示申请/结账", en: "Optimize non-signup forms: lead capture, contact, demo request, checkout"),
        "wonda-cli": .init(desc: "Wonda 终端创作：图/视频/音乐+社媒调研", en: "Wonda CLI: generate images, video, music, audio plus LinkedIn/Reddit/X research"),
        "free-tool-strategy": .init(desc: "免费工具获客：计算器/生成器当营销资产", en: "Plan free tools as marketing: calculators, generators, engineering-as-marketing"),
        "referral-program": .init(desc: "转介绍体系：推荐/分销/口碑裂变设计", en: "Create and optimize referral, affiliate and word-of-mouth programs"),
        "firecrawl-interact": .init(desc: "抓取页实时操作：点击填表走流程取数", en: "Drive a live browser on scraped pages: click, fill forms, navigate, extract"),
        "stripe-best-practices": .init(desc: "Stripe 集成决策：收单/平台/订阅怎么选", en: "Stripe integration decisions: Checkout vs PaymentIntents, Connect, billing, migrations"),
        "design-md": .init(desc: "Stitch 项目反推设计系统写成 DESIGN.md", en: "Analyze Stitch projects and synthesize a semantic design system into DESIGN.md"),
        "ab-test-setup": .init(desc: "AB 实验：假设/变体/增长实验体系搭建", en: "Plan and implement A/B tests: hypotheses, variants, growth experimentation programs"),
        "tailwind-design-system": .init(desc: "Tailwind v4 设计系统：令牌+组件库", en: "Scalable design systems with Tailwind v4: tokens, component libraries, responsive patterns"),
        "obsidian-markdown": .init(desc: "Obsidian 语法：双链/嵌入/标注/属性", en: "Obsidian Flavored Markdown: wikilinks, embeds, callouts, properties, tags"),
        "notion-api": .init(desc: "Notion API 操作：页面/数据库/块增删改查", en: "Interact with the Notion API via REST: pages, databases, blocks, comments"),
        "signup-flow-cro": .init(desc: "注册流优化：降摩擦防流失提试用激活", en: "Optimize signup and trial activation: reduce friction and dropoff"),
        "paywall-upgrade-cro": .init(desc: "付费墙优化：升级页/加购弹窗/功能门", en: "Create and optimize paywalls, upgrade screens, upsell modals, feature gates"),
        "popup-cro": .init(desc: "弹窗转化：退出挽留/留资弹层不惹人烦", en: "Conversion popups, modals and banners: exit intent, lead capture without annoyance"),
        "typescript-advanced-types": .init(desc: "TS 高级类型：泛型/条件/映射/模板字面量", en: "Advanced TypeScript types: generics, conditional, mapped, template literals, utilities"),
        "typegpu": .init(desc: "WebGPU 合成：WGSL 着色器/粒子/液态玻璃", en: "TypeGPU and raw WebGPU patterns: WGSL shaders, compute pipelines, particles"),
        "music-to-video": .init(desc: "音乐卡点成片：节拍解析驱动全部画面", en: "Beat-synced video from a music track: one analyzer read drives every frame"),
        "react:components": .init(desc: "Stitch 设计转 React 组件：AST 校验", en: "Convert Stitch designs into modular Vite React components with AST validation"),
        "firecrawl-build-search": .init(desc: "产品内建搜索：Firecrawl /search 集成", en: "Integrate Firecrawl /search into product code: query-first discovery then extraction"),
        "firecrawl-build-scrape": .init(desc: "产品内建单页抓取：/scrape 接进代码", en: "Integrate Firecrawl /scrape for single-page extraction: markdown, links, screenshots"),
        "firecrawl-build-interact": .init(desc: "产品内建页面交互：点击填表带登录态", en: "Integrate Firecrawl /interact for dynamic pages: clicks, forms, auth-aware flows"),
        "firecrawl-build-onboarding": .init(desc: "Firecrawl 接入引导：密钥/SDK/环境变量", en: "Get Firecrawl credentials and SDK set up in a project: API key, .env, first SDK"),
        "opentui": .init(desc: "OpenTUI 终端界面：组件/布局/按键/动画", en: "Build terminal UIs with OpenTUI Core, React or Solid: components, layout, keymaps"),
        "resolving-merge-conflicts": .init(desc: "git 合并/变基冲突现场处置", en: "Resolve an in-progress git merge or rebase conflict"),
        "developing-genkit-go": .init(desc: "Genkit Go 开发：生成/流式/工具调用", en: "Build AI apps with Genkit in Go: generation, prompts, streaming, tool calling"),
        "nia": .init(desc: "Nia 万物索引：代码/文档/论文/群聊全检索", en: "Index and search repos, docs, papers, datasets, Slack, Drive and X with Nia AI"),
        "enhance-prompt": .init(desc: "UI 提示词精修：模糊想法变 Stitch 专用", en: "Transform vague UI ideas into polished Stitch-optimized prompts with design context"),
        "firebase-remote-config-basics": .init(desc: "Remote Config：功能开关动态改行为", en: "Firebase Remote Config: templates, feature flags, dynamic app behavior"),
        "claude-api": .init(desc: "Claude API 速查：模型/定价/流式/工具调用/缓存", en: "Claude API / Anthropic SDK reference: model ids, pricing, streaming, tool use, caching"),
        "stitch-loop": .init(desc: "Stitch 自主迭代：接力循环持续建站", en: "Iteratively build websites with Stitch using an autonomous baton-passing loop"),
        "compress": .init(desc: "记忆文件压缩：省 token 留人类可读备份", en: "Compress CLAUDE.md and memory files into caveman format, backup kept human-readable"),
        "native-data-fetching": .init(desc: "Expo 数据请求：缓存/离线/加载器全覆盖", en: "Network requests in Expo: fetch, React Query, SWR, caching, offline, loaders"),
        "amazon-product-research": .init(desc: "亚马逊选品：需求/竞争/利润/入场门槛", en: "Amazon product research: demand, competition, profit potential, market entry"),
        "turborepo": .init(desc: "Turborepo 单仓：任务管道/缓存/过滤", en: "Turborepo monorepo guidance: task pipelines, caching, --filter, CI optimization"),
        "neon-postgres": .init(desc: "Neon 无服务 PG：分支/伸缩/连接池", en: "Neon Serverless Postgres: branching, autoscaling, pooling, CLI, SDKs"),
        "google-agents-cli-adk-code": .init(desc: "ADK 写代码：工具/回调/状态管理范式", en: "Write ADK agent code: tools, callbacks, state management, Python API patterns"),
        "upgrade-stripe": .init(desc: "Stripe API/SDK 版本升级指南", en: "Guide for upgrading Stripe API versions and SDKs"),
        "obsidian-cli": .init(desc: "Obsidian CLI：笔记管理+插件主题开发", en: "Obsidian CLI: read, create, search notes plus plugin and theme development"),
        "google-agents-cli-workflow": .init(desc: "ADK 开发工作流：本地跑到上线监控", en: "ADK dev workflow: run locally, debug, test, deploy, publish, monitor agents"),
        "google-agents-cli-eval": .init(desc: "ADK 评估：评测集/失败分析/质量方法论", en: "Evaluate ADK agents: eval datasets, failure analysis, quality methodology"),
        "google-agents-cli-scaffold": .init(desc: "ADK 项目脚手架：新建/加 CI/升级", en: "Scaffold new ADK agent projects: create, add CI/CD, enhance, upgrade"),
        "google-agents-cli-observability": .init(desc: "ADK 可观测：链路追踪/日志/生产调试", en: "Monitor deployed ADK agents: Cloud Trace, logging, production debugging"),
        "google-agents-cli-deploy": .init(desc: "ADK 部署：Cloud Run/GKE/密钥/流水线", en: "Deploy ADK agents: Agent Runtime, Cloud Run, GKE, CI/CD, secrets"),
        "google-agents-cli-publish": .init(desc: "ADK 发布：注册进 Gemini Enterprise", en: "Publish ADK agents to Gemini Enterprise via agents-cli"),
        "shadcn-ui": .init(desc: "shadcn/ui 实战：找组件/安装/定制", en: "Integrate and build with shadcn/ui: discovery, installation, customization"),
        "obsidian-bases": .init(desc: "Obsidian Bases：笔记库表格视图与公式", en: "Create Obsidian Bases (.base): views, filters, formulas, note databases"),
        "decision-mapping": .init(desc: "决策地图：想法拆成排序工单逐个击破", en: "Turn a loose idea into sequenced investigation tickets, drive each to resolution"),
        "gws-gmail": .init(desc: "Gmail 命令行：收发管理邮件", en: "Gmail via Google Workspace CLI: send, read and manage email"),
        "upgrading-expo": .init(desc: "Expo SDK 升级与依赖问题修理", en: "Upgrade Expo SDK versions and fix dependency issues"),
        "web-search": .init(desc: "Tavily/Exa 联网搜索：研究与 RAG 取料", en: "Web search and content extraction with Tavily and Exa via inference.sh CLI"),
        "agent-tools": .init(desc: "inference.sh 全家：250+ AI 应用一口气", en: "Run 250+ AI apps via inference.sh CLI: image, video, LLMs, search, 3D, automation"),
        "python-executor": .init(desc: "沙箱跑 Python：百余库预装即用", en: "Run Python in a sandbox with 100+ preinstalled libraries: pandas, OpenCV, Playwright"),
        "infsh-cli": .init(desc: "infsh 命令行：生成/搜索/自动化总入口", en: "inference.sh CLI entry: run 250+ AI apps for generation, search and automation"),
        "competitor-profiling": .init(desc: "竞品画像：给网址出竞争情报档案", en: "Research and profile competitors from URLs: competitive intelligence reports"),
        "expo-tailwind-setup": .init(desc: "Expo 配 Tailwind v4：全端统一样式", en: "Set up Tailwind v4 in Expo with react-native-css and NativeWind v5"),
        "stripe-projects": .init(desc: "Stripe Projects 开资源：库/鉴权/缓存", en: "Provision infrastructure via Stripe Projects: databases, auth, caching, hosting"),
        "media-use": .init(desc: "素材总管：BGM/音效/图标解析落盘登记", en: "Agent Media OS: resolve any BGM, SFX, image or icon into a frozen local file"),
        "community-marketing": .init(desc: "社群营销：建群运营养出品牌自来水", en: "Build communities that drive growth: Discord, Slack, forums, brand advocates"),
        "expo-deployment": .init(desc: "EAS 发布：双商店提审/版本/元数据", en: "Deploy Expo apps with EAS: App Store, Play Store, TestFlight, versions, ASO"),
        "arrange": .init(desc: "排布优化：治单调网格/乱间距/弱层级", en: "Improve layout, spacing and visual rhythm: fix monotonous grids and weak hierarchy"),
        "expo-dev-client": .init(desc: "Expo 开发客户端构建", en: "Build an Expo app for development with a custom dev client"),
        "agentix-ceo": .init(desc: "Agent 团队管理：设岗派活/开工监工", en: "Manage an agent team: create roles, assign tasks, spawn workers, monitor progress"),
        "solana-dev": .init(desc: "Solana 开发：Anchor 合约/代币/钱包", en: "Build Solana dapps: Anchor programs, tokens, wallets, PDAs, devnet deploys"),
        "json-canvas": .init(desc: "Obsidian 白板文件：节点连线画思维导图", en: "Create JSON Canvas files: nodes, edges, groups for mind maps and flowcharts"),
        "expo-cicd-workflows": .init(desc: "EAS 工作流 YAML：构建流水线自动化", en: "Write EAS workflow YAML for Expo: build pipelines and deployment automation"),
        "pexo-agent": .init(desc: "全自动成片：文/图/链接进，多镜头片出", en: "Finished multi-shot AI video from text, images or URLs with auto model selection"),
        "gws-drive": .init(desc: "Google Drive 命令行：文件目录共享盘", en: "Google Drive via CLI: manage files, folders and shared drives"),
        "nodejs-backend-patterns": .init(desc: "Node 后端范式：中间件/鉴权/API 设计", en: "Production Node.js backends: Express/Fastify, middleware, auth, API design"),
        "firecrawl-parse": .init(desc: "本地文件转 Markdown：PDF/Word/表格", en: "Parse local files (PDF, DOCX, XLSX, HTML) into clean markdown on disk"),
        "directory-submissions": .init(desc: "目录站投放：拿外链提权重蹭曝光", en: "Submit products to startup, SaaS and AI directories for backlinks and discovery"),
        "image": .init(desc: "营销出图：博客头图/社媒图/品牌素材", en: "Create and optimize marketing images: blog heroes, social graphics, brand assets"),
        "make-interfaces-feel-better": .init(desc: "界面手感工程：悬停/阴影/微动效细节", en: "Design engineering principles for polished interfaces: hover, shadows, micro-motion"),
        "video": .init(desc: "营销视频制片：AI 工具与代码框架全谱", en: "Produce marketing video with AI tools: Remotion, HeyGen, Veo, Sora, Runway, Kling"),
        "ai-sdk": .init(desc: "AI SDK 参考：生成/流式/智能体/RAG", en: "Vercel AI SDK: generateText, streamText, agents, chatbots, RAG, tools"),
        "git-commit": .init(desc: "规范化提交：智能暂存+自动生成信息", en: "Conventional commits with intelligent staging and message generation"),
        "gws-docs": .init(desc: "Google 文档命令行读写", en: "Read and write Google Docs from the CLI"),
        "expo-api-routes": .init(desc: "Expo Router API 路由+EAS 托管", en: "Create API routes in Expo Router with EAS Hosting"),
        "cross-border-ecommerce": .init(desc: "跨境电商顾问：八维评分选市场配履约", en: "Cross-border e-commerce advisor: score markets on 8 dimensions, compare fulfillment"),
        "firebase-firestore-standard": .init(desc: "Firestore 标准版：开通/规则/SDK", en: "Firestore Standard Edition: provisioning, security rules, SDK usage"),
        "gws-calendar": .init(desc: "Google 日历命令行：日程管理", en: "Google Calendar via CLI: manage calendars and events"),
        "gws-sheets": .init(desc: "Google 表格命令行读写", en: "Google Sheets via CLI: read and write spreadsheets"),
        "firebase-firestore-enterprise-native-mode": .init(desc: "Firestore 企业原生版：建模/规则/SDK", en: "Firestore Enterprise native mode: provisioning, data model, security rules, SDK"),
        "huashu-design": .init(desc: "花叔Design：HTML 高保真原型/PPT/动画/评审", en: "Huashu Design: high-fidelity HTML prototypes, slides, animations and expert review"),
        "humanizer-zh": .init(desc: "中文去 AI 味：修夸饰/套话/破折号滥用", en: "Remove AI writing tells from Chinese text based on Wikipedia's AI-signs guide"),
        "python-appservice-deploy": .init(desc: "Python 应用部署 Azure App Service", en: "Deploy Python (Flask/Django/FastAPI) code to Azure App Service Linux"),
        "planning-with-files": .init(desc: "文件化规划：计划进度落盘，清上下文不丢", en: "Manus-style persistent planning: task_plan.md and progress.md survive context loss"),
        "talking-head-recut": .init(desc: "口播视频包装：字卡/数据/引用贴片跟稿走", en: "Layer timed graphic overlays onto talking-head video: titles, callouts, quotes"),
        "firebase-ai-logic": .init(desc: "Firebase AI Logic：Gemini 接入网页应用", en: "Integrate Firebase AI Logic (Gemini API): setup, multimodal, structured output"),
        "accessibility": .init(desc: "无障碍审计：WCAG 2.2/读屏/键盘导航", en: "Audit and improve web accessibility per WCAG 2.2: screen readers, keyboard nav"),
        "golang-code-style": .init(desc: "Go 代码风格：断行/声明/控制流可读性", en: "Go code style conventions: line breaking, declarations, control flow clarity"),
        "developing-genkit-python": .init(desc: "Genkit Python：AI 流程工具与排错", en: "Build AI apps with Genkit in Python: agents, flows, tools, troubleshooting"),
        "golang-error-handling": .init(desc: "Go 错误处理：包装/判断/哨兵/结构化日志", en: "Idiomatic Go errors: wrapping with %w, errors.Is/As, sentinels, slog logging"),
        "seo-geo": .init(desc: "SEO+GEO 双优化：传统搜索和 AI 搜索都要", en: "SEO and GEO: keywords, schema markup, optimize for AI and traditional search"),
        "golang-performance": .init(desc: "Go 性能优化：降分配/调 GC/池化热路径", en: "Go performance playbook: allocation, GC tuning, pooling, hot-path optimization"),
        "replicas-agent": .init(desc: "Replicas 云工位：后台编码代理行动指南", en: "Guide for background coding agents running inside Replicas cloud workspaces"),
        "golang-design-patterns": .init(desc: "Go 设计模式：函数选项/注入/优雅退出", en: "Idiomatic Go patterns: functional options, DI, graceful shutdown, resilience"),
        "golang-testing": .init(desc: "Go 测试大全：表驱动/模糊/泄漏检测", en: "Production Go tests: table-driven, testify, fuzzing, goleak, snapshots, coverage"),
        "anysearch": .init(desc: "实时搜索引擎：垂类/批量并发/URL 抽取", en: "Real-time search: web, vertical domains, parallel batch queries, URL extraction"),
        "self-improving-agent": .init(desc: "自进化 Agent：三层记忆+钩子自纠错", en: "Self-improving agent with semantic, episodic and working memory plus hook-based fixes"),
        "gsap-core": .init(desc: "GSAP 官方核心：补间/缓动/交错/响应式", en: "Official GSAP core skill: tweens, easing, stagger, matchMedia responsiveness"),
        "cloudflare": .init(desc: "Cloudflare 全平台：Workers/存储/AI/安全", en: "Cloudflare platform: Workers, Pages, KV/D1/R2, Workers AI, WAF, Terraform"),
        "shape": .init(desc: "写码前定设计：访谈产出设计简报", en: "Plan UX/UI before code: structured discovery interview producing a design brief"),
        "gsap-scrolltrigger": .init(desc: "ScrollTrigger 官方：滚动动画/钉住/视差", en: "Official GSAP ScrollTrigger: scroll-linked animations, pinning, scrub, parallax"),
        "vercel-optimize": .init(desc: "Vercel 降本提速：按指标排查出优化清单", en: "Vercel cost and performance optimization: metric-backed, ranked recommendations"),
        "writing-guidelines": .init(desc: "文档文风审查：按写作手册对标", en: "Review docs and prose for Writing Guidelines compliance: style, voice, tone"),
        "skill-seekers": .init(desc: "文档变技能：官网/仓库/PDF 一键炼成 skill", en: "Auto-build AI skills from docs sites, repos, PDFs and videos with source detection"),
        "reddit-fetch": .init(desc: "Reddit 内容抓取：JSON API 绕 403 封锁", en: "Fetch Reddit content via the curl JSON API, works when Reddit blocks with 403"),
        "notebooklm": .init(desc: "直连 NotebookLM：只答文档内容带引用", en: "Query Google NotebookLM notebooks for source-grounded, citation-backed answers"),
        "playwright-skill": .init(desc: "Playwright 全能自动化：识别端口测页面", en: "Complete Playwright browser automation: auto-detect dev servers, test, screenshot"),
        "prompt-engineering": .init(desc: "提示词工程：命令/钩子/子代理提示优化", en: "Prompt engineering for commands, hooks, skills and subagent prompts"),
        "ios-simulator-skill": .init(desc: "iOS 模拟器工具箱：29 脚本测试构建导航", en: "29 scripts for iOS testing and automation: semantic UI navigation, builds, a11y"),
    ]
}
