import Foundation

// 精选目录（v2.3，v2.14 双语化+热门扩容）：常见 skill 的一句话简介 + 类型提示，编译进二进制。
// 显示优先级：目录简介 > frontmatter description（上游英文长文案不再直出卡片）；
// 本地完整文档不受影响——详情 peek 摘要与「在编辑器中打开」仍读真实文件。
// 类型优先级：frontmatter 显式 type: > 目录提示 > 名称特征。
// 双语：desc = 中文，en = 英文；界面语言挑面，缺英文落回中文（半成品好过空白）。
// 热门扩容数据在 CatalogHot.swift（脚本生成，整文件可重生成），本文件手工维护。

struct CatalogEntry {
    let desc: String
    var en: String? = nil
    var type: CapType? = nil
    /// 来源提示（v2.4）：复制安装类 skill（如 guanskill 套娃）四级溯源全落空时，
    /// 由目录补一手——能归拢成套装
    var source: String? = nil
    /// 界面语言取词：中文界面 → desc；其它 → en（缺则落回 desc）
    var localizedDesc: String { l10nIsChinese ? desc : (en ?? desc) }
}

enum Catalog {
    /// 手工精选优先，热门扩容兜底（同名时手工版赢——它更懂本地语境）
    static func entry(_ name: String) -> CatalogEntry? { skills[name] ?? CatalogHot.skills[name] }

    static let skills: [String: CatalogEntry] = [
        // ── Anthropic 官方 ──────────────────────────────
        "skill-creator": .init(desc: "创建、改进与评测 Agent Skill 的官方脚手架",
                               en: "Official scaffold to create, improve and evaluate Agent Skills"),
        "docx": .init(desc: "Word 文档读写创建（Anthropic 官方）",
                      en: "Read, write and create Word documents (Anthropic official)"),
        "pdf": .init(desc: "PDF 读取、生成与处理（Anthropic 官方）",
                     en: "Read, generate and process PDFs (Anthropic official)"),
        "pptx": .init(desc: "PPT 幻灯片读写创建（Anthropic 官方）",
                      en: "Read, write and create PowerPoint decks (Anthropic official)"),
        "xlsx": .init(desc: "Excel 表格读写创建（Anthropic 官方）",
                      en: "Read, write and create Excel spreadsheets (Anthropic official)"),
        "consolidate-memory": .init(desc: "记忆文件整理：去重、修正、修剪索引",
                                    en: "Tidy memory files: dedupe, fix and prune the index"),

        // ── 宝玉系（jimliu/baoyu-skills）────────────────
        "baoyu-article-illustrator": .init(desc: "文章配图：分析结构定位置，类型×风格×配色三维生成",
                                           en: "Article illustration: type × style × palette generation at analyzed positions"),
        "baoyu-comic": .init(desc: "知识漫画：分镜脚本 + 多画风批量生成",
                             en: "Knowledge comics: panel scripts + multi-style batch generation"),
        "baoyu-compress-image": .init(desc: "图片压缩：自动选工具转 WebP / PNG",
                                      en: "Image compression to WebP/PNG with automatic tool selection"),
        "baoyu-cover-image": .init(desc: "文章封面图：11 配色 × 7 渲染风格组合",
                                   en: "Article covers: 11 palettes × 7 rendering styles"),
        "baoyu-danger-gemini-web": .init(desc: "逆向 Gemini Web 的图文生成后端",
                                         en: "Image/text generation backend via reverse-engineered Gemini Web"),
        "baoyu-danger-x-to-markdown": .init(desc: "X 推文 / 文章转 Markdown（逆向 API）",
                                            en: "X tweets/articles to Markdown (reverse-engineered API)"),
        "baoyu-diagram": .init(desc: "深色系专业 SVG 图：架构 / 流程 / 时序 / 脑图全类型",
                               en: "Dark-themed professional SVG diagrams: architecture, flow, sequence, mind maps"),
        "baoyu-electron-extract": .init(desc: "拆 Electron 应用 asar 包，还原源码与资源",
                                        en: "Unpack Electron asar bundles to recover sources and assets"),
        "baoyu-format-markdown": .init(desc: "Markdown 美化：frontmatter / 标题 / 摘要 / 代码块",
                                       en: "Markdown formatting: frontmatter, titles, summaries, code blocks"),
        "baoyu-image-cards": .init(desc: "信息图卡片组：12 风格 × 8 版式社媒种草图",
                                   en: "Infographic card sets: 12 styles × 8 layouts for social media"),
        "baoyu-image-gen": .init(desc: "AI 生图聚合：GPT Image / Gemini / 即梦 / Seedream 等",
                                 en: "Image generation hub: GPT Image, Gemini, Jimeng, Seedream and more"),
        "baoyu-imagine": .init(desc: "AI 生图聚合：多供应商文生图 + 参考图",
                               en: "Multi-provider text-to-image with reference image support"),
        "baoyu-infographic": .init(desc: "高密度信息大图：21 版式 × 22 视觉风格",
                                   en: "High-density infographics: 21 layouts × 22 visual styles"),
        "baoyu-markdown-to-html": .init(desc: "Markdown 转微信兼容 HTML：高亮 / 公式 / Mermaid",
                                        en: "Markdown to WeChat-compatible HTML: highlighting, math, Mermaid"),
        "baoyu-post-to-wechat": .init(desc: "发布微信公众号：文章 + 贴图双形态",
                                      en: "Publish to WeChat Official Account: articles and image posts"),
        "baoyu-post-to-weibo": .init(desc: "发微博：普通帖 + 头条文章",
                                     en: "Post to Weibo: regular posts and headline articles"),
        "baoyu-post-to-x": .init(desc: "发 X/Twitter：推文 + 长文 Article",
                                 en: "Post to X/Twitter: tweets and long-form Articles"),
        "baoyu-slide-deck": .init(desc: "内容转幻灯片图组：大纲 + 逐页生成",
                                  en: "Content to slide deck images: outline plus per-slide generation"),
        "baoyu-summarize": .init(desc: "长文三段式摘要：结论 → 论据 → 关键引文",
                                 en: "Three-part long-form summary: conclusion, evidence, key quotes"),
        "baoyu-translate": .init(desc: "三档翻译（快翻 / 普通 / 精翻），支持术语表",
                                 en: "Three-tier translation (quick/normal/refined) with glossary support"),
        "baoyu-url-to-markdown": .init(desc: "任意 URL 转 Markdown：X / YouTube / HN 专用适配",
                                       en: "Any URL to Markdown with adapters for X, YouTube, Hacker News"),
        "baoyu-wechat-summary": .init(desc: "微信群聊精华摘要（wx-cli 本地抓取）",
                                      en: "WeChat group chat digest via local wx-cli capture"),
        "baoyu-xhs-images": .init(desc: "小红书图文卡片组：12 风格社媒信息图",
                                  en: "Xiaohongshu image card sets: 12-style social infographics"),
        "baoyu-youtube-transcript": .init(desc: "下载 YouTube 字幕与封面，支持翻译和章节",
                                          en: "Download YouTube transcripts and covers with translation and chapters"),

        // ── 飞书系（open.feishu.cn well-known）──────────
        "lark-approval": .init(desc: "飞书审批：待办查询与处理",
                               en: "Feishu approval: query and process pending items"),
        "lark-apps": .init(desc: "本地 HTML 一键部署成飞书妙搭公网应用",
                           en: "Deploy local HTML as a public Feishu Miaoda app in one step"),
        "lark-attendance": .init(desc: "飞书考勤：查自己的打卡记录",
                                 en: "Feishu attendance: check your own clock-in records"),
        "lark-base": .init(desc: "飞书多维表格全操作：表 / 字段 / 记录 / 视图 / 仪表盘",
                           en: "Feishu Base full ops: tables, fields, records, views, dashboards"),
        "lark-calendar": .init(desc: "飞书日历：日程 / 会议室 / 忙闲查询",
                               en: "Feishu calendar: events, meeting rooms, free-busy queries"),
        "lark-contact": .init(desc: "飞书通讯录：姓名 ⇄ open_id 互查",
                              en: "Feishu contacts: resolve names ⇄ open_ids"),
        "lark-doc": .init(desc: "飞书云文档读写编辑（Docx / Wiki）",
                          en: "Read and edit Feishu cloud docs (Docx / Wiki)"),
        "lark-drive": .init(desc: "飞书云空间：上传下载 / 导入在线文档 / 权限",
                            en: "Feishu Drive: upload/download, import online docs, permissions"),
        "lark-event": .init(desc: "飞书事件流监听：NDJSON 实时消费",
                            en: "Feishu event stream listener with real-time NDJSON output"),
        "lark-im": .init(desc: "飞书消息：收发 / 搜索 / 群管理 / 文件",
                         en: "Feishu IM: send/receive, search, group management, files"),
        "lark-mail": .init(desc: "飞书邮箱：写发读搜 + 草稿 / 规则 / 附件",
                           en: "Feishu mail: compose, send, read, search plus drafts, rules, attachments"),
        "lark-markdown": .init(desc: "飞书 Markdown 文件查看、编辑与比较",
                               en: "View, edit and diff Markdown files in Feishu"),
        "lark-minutes": .init(desc: "飞书妙记：搜索 / 下载 / 上传生成",
                              en: "Feishu Minutes: search, download, upload to generate"),
        "lark-note": .init(desc: "飞书会议纪要直查：note_id 详情与逐字稿",
                           en: "Feishu meeting notes: details and transcripts by note_id"),
        "lark-okr": .init(desc: "飞书 OKR：周期 / 目标 / 关键结果管理",
                          en: "Feishu OKR: cycles, objectives and key results"),
        "lark-openapi-explorer": .init(desc: "飞书原生 OpenAPI 探索（CLI 未封装接口）",
                                       en: "Explore native Feishu OpenAPIs beyond the CLI wrappers"),
        "lark-shared": .init(desc: "lark-cli 认证与身份切换基础件",
                             en: "lark-cli auth and identity-switch foundation"),
        "lark-sheets": .init(desc: "飞书电子表格：建表 / 行列 / 数据 / 样式",
                             en: "Feishu Sheets: create tables, rows/columns, data, styles"),
        "lark-skill-maker": .init(desc: "把飞书 API 封装成自定义 Skill",
                                  en: "Wrap Feishu APIs into custom reusable skills"),
        "lark-slides": .init(desc: "飞书幻灯片创建与编辑",
                             en: "Create and edit Feishu Slides"),
        "lark-task": .init(desc: "飞书任务：待办 / 清单 / 子任务",
                           en: "Feishu tasks: todos, lists, subtasks"),
        "lark-vc": .init(desc: "飞书视频会议：历史会议 / 纪要 / 参会人查询",
                         en: "Feishu VC: past meetings, minutes, participant queries"),
        "lark-vc-agent": .init(desc: "飞书会议机器人：代入会 + 实时事件",
                               en: "Feishu meeting bot: join on behalf plus real-time events"),
        "lark-whiteboard": .init(desc: "飞书画板节点读取与导出",
                                 en: "Read and export Feishu whiteboard nodes"),
        "lark-wiki": .init(desc: "飞书知识库：空间 / 节点 / 成员管理",
                           en: "Feishu Wiki: spaces, nodes, member management"),
        "lark-workflow-meeting-summary": .init(desc: "工作流：批量汇总会议纪要成报告",
                                               en: "Workflow: batch-summarize meeting minutes into reports"),
        "lark-workflow-standup-report": .init(desc: "工作流：日程 + 待办生成站会摘要",
                                              en: "Workflow: standup digest from calendar and todos"),

        // ── 观远系（guanskill）──────────────────────────
        "guancli": .init(desc: "观远 BI 全能查询：ETL / 数据集 / 页面 / 血缘 / 指标",
                         en: "Guandata BI querying: ETL, datasets, pages, lineage, metrics",
                         type: .cli, source: "npm:@guandata/guanskill"),
        "guands": .init(desc: "观远数据连接与数据集管理：增量 / 调度 / 计算字段",
                        en: "Guandata connections and datasets: incremental sync, schedules, computed fields",
                        source: "npm:@guandata/guanskill"),
        "guanetl": .init(desc: "观远 ETL 全流程：拉取 / 编辑 / 预览 / 发布 / 调度",
                         en: "Guandata ETL lifecycle: pull, edit, preview, publish, schedule",
                         source: "npm:@guandata/guanskill"),
        "guanvis": .init(desc: "观远卡片与仪表板搭建：30+ 图表类型脚本化",
                         en: "Guandata cards and dashboards: 30+ chart types as scripts",
                         source: "npm:@guandata/guanskill"),
        "guanwf": .init(desc: "观远工作流引擎数据流：创建 / 编辑 / 运行",
                        en: "Guandata workflow engine dataflows: create, edit, run",
                        source: "npm:@guandata/guanskill"),

        // ── 马甲自研 ────────────────────────────────────
        "majia-getnote": .init(desc: "得到 Get 笔记一站式：存搜管 + 订阅抓取总结",
                               en: "Get-Note all-in-one: save, search, manage plus feed digests"),
        "majia-guanyuan": .init(desc: "观远 BI 实战增益层：77 ETL 战例 + 30 条法则",
                                en: "Guandata BI field guide: 77 ETL cases and 30 rules"),
        "majia-human-txt": .init(desc: "去 AI 味写作辅助：直写 / 陪写双角色",
                                 en: "De-AI writing aid with direct-write and co-write modes"),
        "majia-ota-app": .init(desc: "Mac app 发布全链：签名 / 公证 / Sparkle / 落地页",
                               en: "Mac app shipping pipeline: codesign, notarize, Sparkle, landing page"),
        "majia-ota-skill": .init(desc: "Agent Skill 发布全链：同步 / 审计 / 发布 / 伞形",
                                 en: "Agent Skill release pipeline: sync, audit, publish, umbrella"),
        "majia-quanyu-jpg": .init(desc: "飞书文章杂志水彩全套配图 + 公众号封面",
                                  en: "Magazine-watercolor illustration sets and WeChat covers for articles"),
        "majia-skill-manager": .init(desc: "本机 skill 服务台：装 / 删 / 链 / 巡检",
                                     en: "Local skill service desk: install, remove, link, inspect"),
        "majia-speech": .init(desc: "文字转语音合成（马甲定制）",
                              en: "Text-to-speech synthesis (Majia custom)"),
        "majia-tupian": .init(desc: "飞书文章杂志水彩全套配图 + 公众号封面",
                              en: "Magazine-watercolor illustration sets and WeChat covers for articles"),
        "majia-video-png": .init(desc: "视频抽帧转 PNG 截图集",
                                 en: "Extract video frames into PNG screenshot sets"),
        "majia-voice-corpus": .init(desc: "我的声音语料库：录音发言结构化归档",
                                    en: "Voice corpus: structured archive of transcribed speech"),
        "majia-wenzi": .init(desc: "去 AI 味写作辅助：直写 / 陪写双角色",
                             en: "De-AI writing aid with direct-write and co-write modes"),

        // ── 社区常用 ────────────────────────────────────
        "agent-reach": .init(desc: "给 Agent 装上全网之眼：17 个平台的 CLI 触达",
                             en: "Give agents web-wide reach: CLI access to 17 platforms"),
        "anything-to-notebooklm": .init(desc: "多源内容进 NotebookLM：转播客 / PPT / 思维导图",
                                        en: "Any source into NotebookLM: podcasts, decks, mind maps"),
        "claude-to-im": .init(desc: "Claude Code 桥接到飞书 / TG / Discord，手机上聊",
                              en: "Bridge Claude Code to Feishu/Telegram/Discord for mobile chat"),
        "defuddle": .init(desc: "网页正文净化抽取：去广告导航留正文",
                          en: "Clean article extraction: strip ads and nav, keep the content"),
        "dbs": .init(desc: "dontbesilent 商业工具箱主入口：问题自动路由",
                     en: "dontbesilent business toolkit entry with automatic routing"),
        "ima-skill": .init(desc: "腾讯 ima 知识库与笔记操作",
                           en: "Tencent ima knowledge base and notes operations"),
        "knowledge-site-creator": .init(desc: "一句话生成领域知识学习网站并部署上线",
                                        en: "One prompt to generate and deploy a knowledge-learning site"),
        "nmem-cli": .init(desc: "Nowledge Mem 记忆库 CLI：存查 + 知识图谱",
                          en: "Nowledge Mem CLI: store, search and knowledge graph", type: .cli),
        "qiaomu-design-advisor": .init(desc: "设计顾问：配色 / 排版 / 组件建议",
                                       en: "Design advisor: palettes, typography, component suggestions"),
        "qiaomu-music-player-spotify": .init(desc: "Spotify 播放控制",
                                             en: "Spotify playback control"),
        "yt-search-download": .init(desc: "YouTube 搜索 + 下载",
                                    en: "YouTube search and download"),
    ]
}
