#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_DIR="$ROOT_DIR/build/Popskill.app"
CONTENTS_DIR="$APP_DIR/Contents"
MACOS_DIR="$CONTENTS_DIR/MacOS"
RESOURCES_DIR="$CONTENTS_DIR/Resources"
FRAMEWORKS_DIR="$CONTENTS_DIR/Frameworks"
# 版本/build 单源在仓库根 VERSION 文件（第一行版本号，第二行 build），env 可覆盖。
# 曾经默认值钉死 2.0.0/200——漏传 env 就产出错版二进制（v2.8 审计修复）。
# build number 与版本号解耦、单调递增（去点方案在 x.y.10 时会让 Sparkle 更新链断裂）。
VERSION_FILE="$ROOT_DIR/VERSION"
if [[ ! -f "$VERSION_FILE" ]]; then
  echo "缺少 VERSION 文件（第一行版本号，第二行 build number）" >&2
  exit 64
fi
APP_VERSION="${POPSKILL_APP_VERSION:-$(sed -n '1p' "$VERSION_FILE")}"
APP_BUILD="${POPSKILL_APP_BUILD:-$(sed -n '2p' "$VERSION_FILE")}"
if [[ -z "$APP_VERSION" || -z "$APP_BUILD" ]]; then
  echo "VERSION 文件不完整：需要第一行版本号、第二行 build number" >&2
  exit 64
fi
BUNDLE_IDENTIFIER="${POPSKILL_BUNDLE_IDENTIFIER:-com.majia.popskill}"
ICON_SRC="$ROOT_DIR/swift-app/Resources/AppIcon.icns"
# Sparkle defaults — every release after v1.0.0 carries these so the binary
# can check the appcast for updates. The public key is the pair of the
# private key stored in majia's Keychain (managed by Sparkle's generate_keys
# tool; never committed). The feed URL is served by GitHub Pages from
# `main:/docs/appcast.xml`.
DEFAULT_SPARKLE_FEED_URL="https://maojiebc.github.io/majia-Popskill/appcast.xml"
DEFAULT_SPARKLE_PUBLIC_ED_KEY="h7HOqj21MlKe5UJFFa9GKBmV6MtdlcDSeJa9rmAguq8="
: "${POPSKILL_SPARKLE_FEED_URL:=$DEFAULT_SPARKLE_FEED_URL}"
: "${POPSKILL_SPARKLE_PUBLIC_ED_KEY:=$DEFAULT_SPARKLE_PUBLIC_ED_KEY}"
export POPSKILL_SPARKLE_FEED_URL POPSKILL_SPARKLE_PUBLIC_ED_KEY

run_quietly() {
  local log_file
  log_file="$(mktemp)"
  if ! "$@" > "$log_file" 2>&1; then
    cat "$log_file" >&2
    rm -f "$log_file"
    return 1
  fi
  rm -f "$log_file"
}

"$ROOT_DIR/scripts/swiftpm.sh" build -c release --package-path "$ROOT_DIR/swift-app"

rm -rf "$APP_DIR"
mkdir -p "$MACOS_DIR" "$RESOURCES_DIR" "$FRAMEWORKS_DIR"

cp "$ROOT_DIR/swift-app/.build/release/Popskill" "$MACOS_DIR/Popskill"
chmod +x "$MACOS_DIR/Popskill"

# 本地化资源 bundle（v2.12）——Bundle.module 在 .app 里从 Contents/Resources/ 找它,
# 不带上它 app 启动直接 fatalError
L10N_BUNDLE="$ROOT_DIR/swift-app/.build/release/Popskill_Popskill.bundle"
if [[ -d "$L10N_BUNDLE" ]]; then
  ditto "$L10N_BUNDLE" "$RESOURCES_DIR/Popskill_Popskill.bundle"
else
  echo "error: 找不到 $L10N_BUNDLE（资源 bundle 没构建出来？）" >&2
  exit 70
fi

# App icon — generated by scripts/generate-app-icon.swift. Skip silently if
# the icon hasn't been generated yet.
if [[ -f "$ICON_SRC" ]]; then
  cp "$ICON_SRC" "$RESOURCES_DIR/AppIcon.icns"
fi

SPARKLE_FRAMEWORK="$(find "$ROOT_DIR/swift-app/.build/artifacts" -path "*/Sparkle.framework" -type d 2>/dev/null | sort | head -n 1 || true)"
if [[ -n "$SPARKLE_FRAMEWORK" ]]; then
  ditto "$SPARKLE_FRAMEWORK" "$FRAMEWORKS_DIR/Sparkle.framework"
  if ! otool -l "$MACOS_DIR/Popskill" | grep -q "@executable_path/../Frameworks"; then
    run_quietly install_name_tool -add_rpath "@executable_path/../Frameworks" "$MACOS_DIR/Popskill"
  fi
fi

cat > "$CONTENTS_DIR/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleExecutable</key>
  <string>Popskill</string>
  <key>CFBundleIdentifier</key>
  <string>$BUNDLE_IDENTIFIER</string>
  <key>CFBundleName</key>
  <string>Popskill</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleShortVersionString</key>
  <string>$APP_VERSION</string>
  <key>CFBundleVersion</key>
  <string>$APP_BUILD</string>
  <key>CFBundleIconFile</key>
  <string>AppIcon</string>
  <key>LSMinimumSystemVersion</key>
  <string>14.0</string>
  <key>LSApplicationCategoryType</key>
  <string>public.app-category.developer-tools</string>
  <key>CFBundleDevelopmentRegion</key>
  <string>zh-Hans</string>
  <key>CFBundleLocalizations</key>
  <array>
    <string>zh-Hans</string>
    <string>en</string>
  </array>
  <key>NSHighResolutionCapable</key>
  <true/>
  <key>NSHumanReadableCopyright</key>
  <string>Copyright © 2026 majia. All rights reserved.</string>
</dict>
</plist>
PLIST

if [[ -n "${POPSKILL_SPARKLE_FEED_URL:-}" ]]; then
  /usr/libexec/PlistBuddy -c "Add :SUFeedURL string ${POPSKILL_SPARKLE_FEED_URL}" "$CONTENTS_DIR/Info.plist"
fi

if [[ -n "${POPSKILL_SPARKLE_PUBLIC_ED_KEY:-}" ]]; then
  /usr/libexec/PlistBuddy -c "Add :SUPublicEDKey string ${POPSKILL_SPARKLE_PUBLIC_ED_KEY}" "$CONTENTS_DIR/Info.plist"
fi

# Sparkle 自动检查：默认开 + 24 小时间隔（v2.8 起回归 Sparkle 默认节奏；
# 设置页有开关，用户可关；同日多版本场景用「检查 App 更新…」手动覆盖）
/usr/libexec/PlistBuddy -c "Add :SUEnableAutomaticChecks bool true" "$CONTENTS_DIR/Info.plist"
/usr/libexec/PlistBuddy -c "Add :SUScheduledCheckInterval integer 86400" "$CONTENTS_DIR/Info.plist"

if command -v codesign > /dev/null 2>&1; then
  if [[ -d "$FRAMEWORKS_DIR/Sparkle.framework" ]]; then
    run_quietly codesign --force --sign - "$FRAMEWORKS_DIR/Sparkle.framework"
  fi
  run_quietly codesign --force --sign - "$MACOS_DIR/Popskill"
  run_quietly codesign --force --sign - "$APP_DIR"
fi

echo "$APP_DIR"
